### ISSUE TITLE
RealArray append() Issue

### ISSUE THREAD

**Issue by gengkunling** [aleph7/Surge#27]
Hi,

I am using this the append() method of RealArray when encountered the error: 

execution was interrupted reason xc_bad_access (code=exc_i386_invop, subsode=0x0)

The code is in below: 

import UIKit
import Upsurge
var n: RealArray = [1.0, 2.0, 3.0, 4.0, 5.0]
n.append(6.0)

Could you help to resolve this issue?  Thanks!

**Comment by alejandro-isaza** [comment]
RealArrays are fixed-size. That means that you need to explicitly specify the capacity when you construct it. Try this:

```
let n = RealArray(capacity: 6)
n.append(1.0)
n.append(2.0)
```

you can also do this

```
var n: RealArray = [1.0, 2.0, 3.0, 4.0, 5.0, 0.0]
n.count = 5
n.append(6.0)
```

**Comment by alejandro-isaza** [comment]
I added [more info to the Readme file](https://github.com/aleph7/Upsurge#arrays-and-vector-operations) regarding this. Let me know if it helps.

**Comment by gengkunling** [comment]
Thanks a lot! It will be very helpful for the people who start to use the Upsurge.
