### ISSUE TITLE
Complete Tensor

### ISSUE THREAD

**Issue by aidangomez** [aleph7/Surge#33]
- [x] Matrix extraction
- [x] ContiguousMemory Slices + Operations (Accelerate support)
- [ ] NonContiguousMemory Slices
  - [ ] Operations to make Contiguous

**Comment by aidangomez** [comment]
Matrix extraction in @9938319d2b5ff8872d5618d1322168027ab638f8

**Comment by alejandro-isaza** [comment]
Fixed with https://github.com/aleph7/Upsurge/commit/eed4e904722a5c154aee876bc500bd143a3333f0
