### ISSUE TITLE
Converting ValueArraySlice to ValueArray gives me incorrect data

### ISSUE THREAD

**Issue by Somnibyte** [aleph7/Surge#55]
My goal was to convert a ValueArraySlice<Float> to a ValueArray<Float>, but instead of receiving the exact contents of the slice, I received a couple of different values. Here is an example I came across. 

```
let inputMatrix = Matrix<Float>(x)
let vectorSlice = inputMatrix .column(i)  // [3,4]
// The base of 'vectorSlice' is [3,5,8,4,12,15]


```

Now if I were to do the following I would get [3,5] instead of a ValueArray<Float> that has the elements 3,4 like the slice originally had:

`
let vectorSlice = ValueArray(inputMatrix .column(i))  // [3,5]
`

I need the slice to perform a vital operation. My first couple of attempts included what you see above, and something like:

```
        let vectorSlice = inputMatrix .column(i)
        var vector:Array<Float> = []
        for i in vector.startIndex.stride(to: vector.endIndex, by: vector.step) {
           vector.append(vectorSlice.base[i])
        }
```

But this code would be contained in another loop which would result in a higher time complexity. 

How do I successfully convert a ValueArraySlice to a ValueArray?

The [cblas_snrm2](https://developer.apple.com/reference/accelerate/1513250-cblas_snrm2) function, which calculates L2-norm, requires a parameter of type **UnsafePointer<Float>**. ValueArraySlice does not provide a **pointer** field and so I could not satisfy this requirement. This prompted me to proceed to converting it into a ValueArray which has that field.

**Comment by Somnibyte** [comment]
Added more details.

**Comment by Somnibyte** [comment]
I fixed the issue, expect a pull request soon. :)

**Comment by alejandro-isaza** [comment]
`ValueArraySlice`s are not necessarily contiguous. In your case you are going to have a step of 3. That means the first element is base[0] and the second is base[3], which are 3 and 4. If you are going to use the slice as a pointer you need to be aware of this. Let me know if you figured it out! Thanks.

**Comment by alejandro-isaza** [comment]
Fixed via https://github.com/aleph7/Upsurge/commit/63defcb6f58540891c6ef6972d4e09d83a6943fa
