### ISSUE TITLE
Build error with the Playground file

### ISSUE THREAD

**Issue by maelp** [aleph7/Surge#57]
Adding Upsurge to a Cartfile results in this error during build

```
--- xcodebuild: WARNING: Unable to open project file '/Users/primet/tmp/rnnSwift/BrainCore/Carthage/Checkouts/Upsurge/Upsurge.playground' in workspace '/Users/primet/tmp/rnnSwift/BrainCore/Carthage/Checkouts/Upsurge/Upsurge.xcworkspace'.
```

**Comment by alejandro-isaza** [comment]
I get that too, seems to be a problem with Xcode. But it's not an error, the build still succeeds. Are you getting any other errors?

**Comment by maelp** [comment]
No, but this prevents a build from Carthage

On 15 September 2016 at 06:09:40, Alejandro Isaza (notifications@github.com)
wrote:

I get that too, seems to be a problem with Xcode. But it's not an error,
the build still succeeds. Are you getting any other errors?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/aleph7/Upsurge/issues/57#issuecomment-247229521, or mute
the thread

**Comment by alejandro-isaza** [comment]
What version of carthage are you using? Also make sure you are on Xcode 8 and are pointing to version 0.8.0
