### ISSUE TITLE
tile feature

### ISSUE THREAD

**Issue by loudinb** [aleph7/Surge#67]
@aleph7

I would like to propose adding a tile feature to both ValueArray and Matrix.  This would provide similar functionality to _tile_ found in Numpy and _repmat_ found in Matlab.  Below is the code I have implemented in ValueArray.swift

```
    open func toMatrix(rows: Int, columns:Int) -> Matrix<Element> {
        precondition(rows*columns == count, "Element count must equal rows*columns")
        return Matrix(rows: rows, columns: columns, elements: self)
    }
    
    open func tile(m: Int, n: Int) -> Matrix<Element> {
        precondition(m+n >= 1, "Minimum of 1 repeat is required")
        let newCount = (m+1)*(n+1)*count
        let newElements = ValueArray<Element>(count: newCount, repeatedValue: self[0])
        let numberOfCopies = (m+1)*(n+1)
        
        withUnsafeBufferPointer { src in
            newElements.withUnsafeMutableBufferPointer { dest in
                var ptr = dest.baseAddress
                for i in 0..<numberOfCopies {
                    ptr = dest.baseAddress?.advanced(by: i*count)
                    cblas_ccopy(Int32(count), src.baseAddress, 1, ptr, 1)
                }
            }
        }
        return newElements.toMatrix(rows: (m+1), columns: (n+1)*count)
    }
```
And the unit test I added to ValueArrayTests.swift

```
    func testTile() {
        let a: ValueArray<Double> = [1.0, 2.0]
        let b = a.tile(m: 1, n: 1)
        
        XCTAssertEqual(b.count, 8)
        XCTAssertEqual(b.elements, [1.0, 2.0, 1.0, 2.0, 1.0, 2.0, 1.0, 2.0])
    }
```

Is this something you would consider, and would I be able to contribute to Upsurge.

Regards,

Brian

**Comment by alejandro-isaza-hs** [comment]
Yes, that's great. Just make sure to add some docs.

**Comment by alejandro-isaza** [comment]
Yes, that's great. Just make sure to add some docs.

**Comment by loudinb** [comment]
Thank you.  A couple of questions:

1. For documentation, do you have a preference on where to put this?  Are you looking for both inline comments along with a readme with markup for the features?

2. I am working to implement the tile functionality using the vDSP library instead of the cblas library (which I originally used).  I am not sure what the benefits of each library are, is it preferred that vDSP be used where possible over the other libraries in Accelerate?

Thanks,

Brian

**Comment by alejandro-isaza** [comment]
1. Yes it would be great to have both doc comments and something in the README
2. I don't think there there is much difference between those libs. Up to you.

**Comment by loudinb** [comment]
Issue was duplicated by #69
