### ISSUE TITLE
How do you edit a whole row of a Matrix?

### ISSUE THREAD

**Issue by Somnibyte** [aleph7/Surge#68]
I'm aware that there are custom subscripts available for the Matrix class, but I'm not quite sure how to edit a specific row (all of it's values). How do I accomplish this?

**Comment by alejandro-isaza** [comment]
You can do `matrix.row(2) = [1, 2, 3]`

**Comment by Somnibyte** [comment]
I tried this example:

```
var data:[[Float]] = [[1.0, 2.0], [1.0, 3.0]]

var matrix:Matrix<Float> = Matrix(data)

matrix.row(0) = [1.0,3.0]
```
And then I got the error: 

```
Playground execution failed: error: MLKit-PlayGround.playground:11:15: error: cannot assign to value: function call returns immutable value
matrix.row(0) = [1.0,3.0]
~~~~~~~~~~~~~ ^
```

**Comment by alejandro-isaza** [comment]
You are right, Swift doesn't let you return a `struct` that you can mutate. Here is a workaround:
```
var row = d.row(1)
row[2] = 2
```

There is going to be a good solution to this in Swift 4.0 :)

**Comment by Somnibyte** [comment]
Thanks! It worked. :)
