### ISSUE TITLE
Slicing ValueArray and using reduce()

### ISSUE THREAD

**Issue by anasimtiaz** [aleph7/Surge#73]
Hi, just noticed this:

`let a1 : ValueArray<Double> = [1, 2, 3, 4]`
`let a2 : Array<Double> = [1, 2, 3, 4]`

`let a3 = a1[1...3]`
`let a4 = a2[1...3]`
      
`print(a3.reduce(0,+)) \\ 7.0`
`print(a4.reduce(0,+)) \\ 9.0`

Using the reduce() method to sum the contents of sliced array is **missing** the first element when using ValueArray type. To get around this I am basically typecasting the result (for example, the psd) using Array<Double>.

**Comment by alejandro-isaza** [comment]
Should be fixed, thanks for reporting!
