### ISSUE TITLE
Assigning to slices

### ISSUE THREAD

**Issue by carsonfarmer** [aleph7/Surge#76]
Is it possible to assign (say) a `ValueArray<Double>` to a `ValueArraySlice<Double>` in the form of a column or row from a matrix? This is very similar to #68... I'm trying to achieve something like the following to replace specific columns of a matrix with `1`s:

```swift
let d = Matrix<Double>(rows: 5, columns: 5, repeatedValue: 2.0)
var col = d.column(4)
col = ValueArray([1.0, 1.0, 1.0, 1.0, 1.0])
```

Currently I (obviously) get compilation error saying I cannot assign value of type `ValueArray<Double>` to type `ValueArraySlice<Double>`, but is there _some_ way of achieving this that I'm overlooking?

Alternatively, something like the following could be really nice (a la numpy):

```swift
d[0..<5, 4] = ValueArray([1.0, 1.0, 1.0, 1.0, 1.0]) // doesn't compile
```

Rather than the much more verbose (but technically it works):

```swift
d[0...4, 4...4] = ValueArray([3.0, 3.0, 3.0, 3.0, 3.0]).toColumnMatrix()[0...4, 0...0]
// or
d[0...4, 4...4] = Matrix<Double>(rows: 5, columns: 1, repeatedValue: 3.0)[0...4, 0...0]
// or 
d[0...4, 4...4] = ValueArray([3.0]).tile(5, 1)[0...4, 0...0]
```

**Comment by alejandro-isaza** [comment]
I added an `assign` function to all `MutableLinearType`s. You can now do `d.column(4).assign([1.0, 1.0, 1.0, 1.0, 1.0])`

**Comment by keunwoochoi** [comment]
It would be still nicer if we could assign partially: e.g., `d[3..<10] = x`.
