### ISSUE TITLE
Printing/describing MatrixSlice causes EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by carsonfarmer** [aleph7/Surge#77]
This is particularly problematic in a playground, where each line is 'printed' if possible.

```swift
let d = Matrix(rows: 5, columns: 5, repeatedValue: 2.0)
let test = d[0...4, 3...4]
print(test)  // EXC_BAD_ACCESS
```

It looks like the error is cropping up when grabbing the `dimensions` of a `Span` object. But I can't pinpoint where in `MatrixSlice.description` the fix belongs?

**Comment by alejandro-isaza** [comment]
Sorry for the delay, should be fixed now.
