### ISSUE TITLE
ComplexArray Infix operator *= causing crash

### ISSUE THREAD

**Issue by willrichman** [aleph7/Surge#85]
I am attempting to run a project with a real to complex forward FFT operation, and it has a 100% repro EXC_BAD_ACCESS crash on the scaling at the end of the the function.

```swift
    let count = 64
    let frequency = 4.0
    let step = 2.0 * Double.pi / Double(count)
    let x = ValueArray<Double>((0..<count).map({ step * Double($0) * frequency }))
    let fft = FFTDouble(inputLength: x.count)
    let complex = fft.forward(sin(x))  // EXC_BAD_ACCESS here
    for value in complex {
        print(value)
    }
```

The crash is found on line 75 of `FFT.swift`, on the `results *= scale`. As of now this means that real to complex FFTs are broken.

**Comment by alejandro-isaza** [comment]
Good catch, thanks!

**Comment by keunwoochoi** [comment]
Is there a certain way to apply this update (ed54ca6) to my installed package? I installed Upsurge a couple of weeks ago but in my project, the code above (`fft.forward` from real value) crashes as the same line.

**Comment by alejandro-isaza** [comment]
Sorry, forgot to release a new pod. 0.10.1 should be available shortly.

**Comment by keunwoochoi** [comment]
Awesome!
