### ISSUE TITLE
Get error with func column of matrix

### ISSUE THREAD

**Issue by haloking** [aleph7/Surge#86]
Please help fix the error at  A.column(1) when building this
let A = Matrix<Double>([
    [1, 2],
    [3, 4]
    ])
var colValueZero = A.column(0)
print(colValueZero)
var colValueOne = A.column(1)
print(colValueOne)

**Comment by alejandro-isaza** [comment]
Try now, let me know if that works.

**Comment by haloking** [comment]
It works perfectly now, thank you so much!
