### ISSUE TITLE
Potential bug in FFTFloat?

### ISSUE THREAD

**Issue by keunwoochoi** [aleph7/Surge#89]
Hi, thanks for the library!

I couldn't really spot the exact problem here but these are what I've observed.
I'm currently using FFT to compute short-time Fourier transform which is windowing subarray (frame) of a 1D signal and use real(FFT)[:half] of it. It was fine when it's `ValueArray<Double>`/`FFTDouble` but not with `ValueArray<Float>` and `FFTFloat`.

```swift
    let fft_calculator = FFTFloat(inputLength: NSP_FFT)
    let fft_d = FFTDouble(inputLength: NSP_FFT)

    var x2 = ValueArray<Double>((0..< NSP_FFT).map({ sin(0.01 * Double($0)) }))
    var x3 = ValueArray<Float>((0..< NSP_FFT).map({ sin(0.01 * Float($0)) }))
    
    for fr_idx in 0..<n_fr { 
        fft_d.forwardMags(x2)
        fft_calculator.forwardMags(x3)    
    }
```

I think there's a hint in my error message. I've seen two error cases. 

## 1.
In this case, although I was using `FFTFloat` the error often occurs at `FFTDouble` during de-allocating the FFT setup after finishing the computation
Thread 1: signal SIGABRT at `FFT.swift`, line 41, which is part of `FFTDouble` class:
```swift
    deinit {
        vDSP_destroy_fftsetupD(setup)
    }
```

and the error message is
```swift
UpsurgeTest2(93049,0x1068813c0) malloc: *** error for object 0x3fef168f3fef2dc9: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

```

## 2
Some other times, I got this message.

```swift
UpsurgeTest2(93867,0x10c5533c0) malloc: *** error for object 0x7fb62f84a200: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
```

in `ValueArray.swift` line 82.
```swift
 public required init(count: IndexDistance) {
        mutablePointer = UnsafeMutablePointer.allocate(capacity: count) // Thread 1: signal SIGABRT
        self.capacity = count
        self.count = count
    }
```

## Notes
both `.forward` and `.forwardMags` have this problem.

**Comment by alejandro-isaza** [comment]
Interesting. Have you tried enabling address sanitizer, malloc scribble and malloc guard edges? My guess is that there is some size inconsistensies

**Comment by keunwoochoi** [comment]
No I haven’t and actually don’t know how to. But calling some methods of FFTDouble in dealloc-ling FFTFloat seems like a clear bug, no? I’m really a beginner of Swift (moved from Python world) so I’m only guessing though.

On 17 Feb 2018, at 18:10, Alejandro Isaza <notifications@github.com<mailto:notifications@github.com>> wrote:


Interesting. Have you tried enabling address sanitizer, malloc scribble and malloc guard edges? My guess is that there is some size inconsistensies

**Comment by alejandro-isaza** [comment]
Really strange, looks like the FFT step needs double the size of what I thought it needed. Try the latest master.

**Comment by keunwoochoi** [comment]
Thanks, but are you sure it really fixes the problem? The error is still here, `FFTDouble` is fine but `FFTFloat` is not. It seems like the original length computation was already correct for me, too.

Tangential question: in real-FFT, 
```
         results.count = input.count / 2
```
shouldn't it be rather
```
         results.count = input.count / 2 + 1

```
?
