### ISSUE TITLE
convert ValueArray back to Swift array

### ISSUE THREAD

**Issue by keunwoochoi** [aleph7/Surge#93]
Hi, is there a function for this conversion? I couldn't find one. Thanks!

PS. [Numpy <-> Upsurge.md](https://hackmd.io/MYFhDYQEwMwBgLQFNxUSOwkIEYFYo8EAOKARhmJGLhzgGYyg?both) got updated a bit.

**Comment by alejandro-isaza** [comment]
`Array(x)`, added to the doc too.

**Comment by keunwoochoi** [comment]
Awesome, thanks!
