### ISSUE TITLE
Xcode 9.3 beta 3 - 63 compiler errors

### ISSUE THREAD

**Issue by arakweker** [aleph7/Surge#94]
After installing Xcode 9.3 beta 3 I get a whooping 63 compiler errors. The first one is: Type 'ComplexArrayRealSlice<T>' does not conform to protocol 'Collection'. I made a screendump of the other ones. Any thoughts and plans about fixing? Can I already use a branch?
Thanks,
Jan

<img width="237" alt="compiler errors" src="https://user-images.githubusercontent.com/12113265/36951091-95171c60-1fff-11e8-8349-579c79e5fb55.png">

**Comment by alejandro-isaza** [comment]
Fixed on master

**Comment by arakweker** [comment]
Thanks... but after updating to Xcode 9.3 beta 4... another 21 compiler errors.
