### ISSUE TITLE
Xcode 9.3 beta 4 - 21 compiler errors

### ISSUE THREAD

**Issue by arakweker** [aleph7/Surge#95]
After updating Xcode to the latest beta (hoping to get rid of the previous compiler errors) I get another 21 compiler errors.

<img width="255" alt="screen shot 2018-03-07 at 16 17 10" src="https://user-images.githubusercontent.com/12113265/37100395-207307b8-2223-11e8-9763-7919ec651b63.png">

**Comment by alejandro-isaza** [comment]
Are you still having this problem? Did you try the master branch?

**Comment by arakweker** [comment]
Meanwhile I upgraded to Xcode 9.3 beta 4 and iOS 10.3 beta 5. 
Upsurge has 22 compiler errors... so 1 more as when I tried a couple of weeks ago.
The version of Upsurge I installed is 0.10.1

<img width="250" alt="screen shot 2018-03-20 at 19 17 51" src="https://user-images.githubusercontent.com/12113265/37674626-9e2a01d4-2c73-11e8-9467-fce460a34a8d.png">

**Comment by alejandro-isaza** [comment]
I only updated on master, haven't released a Pod yet. Will do that when the final version of Xcode is out. In the meantime you can point your Podfile to master.

**Comment by arakweker** [comment]
I used   pod 'Upsurge', :git => 'https://github.com/alejandro-isaza/Upsurge', :branch => 'master'
Seems to be working now! Thanks.
